use_frameworks!

platform :ios, '9.0'

target 'GonyCustomeCorner_Example' do
  pod 'GonyCustomeCorner', :path => '../'

  target 'GonyCustomeCorner_Tests' do
    inherit! :search_paths

    
  end
end
